spring.application.name=gateway-service
server.port=8080

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.instance.hostname=localhost
#eureka.instance.prefer-ip-address=false

spring.security.jwt.secret-key=gYsjY64oAyIYjGPuvEVe3JSf2M3x6RmFcI73c9qwEet

#spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins[0]=http://localhost:4200
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins[1]=http://localhost:4000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins[2]=https://astra-vastra.vercel.app
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders[0]=Authorization
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders[1]=Content-Type
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].exposedHeaders[0]=Authorization

# Route: Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=authentication-service
#spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTHENTICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# Route 1: User Service
spring.cloud.gateway.server.webflux.routes[1].id=user-service
#spring.cloud.gateway.server.webflux.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/user/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=Authentication

# Route 2: Catalog Service
spring.cloud.gateway.server.webflux.routes[2].id=catalog-service
#spring.cloud.gateway.server.webflux.routes[2].uri=lb://CATALOG-SERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/catalog/**, /api/categories/**
#spring.cloud.gateway.server.webflux.routes[2].filters[0]=Authentication

# Route 3: Inventory Service
spring.cloud.gateway.server.webflux.routes[3].id=inventory-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/inventory/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=Authentication

# Route 4: Order Service
spring.cloud.gateway.server.webflux.routes[4].id=order-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=Authentication

# Block all actuator endpoints
spring.cloud.gateway.server.webflux.routes[5].id=block-actuators
spring.cloud.gateway.server.webflux.routes[5].uri=no://op
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/actuator/**
spring.cloud.gateway.server.webflux.routes[5].filters[0]=SetStatus=403

# Expose actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics

# Health details
management.endpoint.health.show-details=always
