spring.application.name=discovery-service

server.port= 8761

eureka.client.register-with-eureka= false
eureka.client.fetch-registry= false

# Fix hostname
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false